# Generated by Django 5.0 on 2023-12-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh\t'), ('Karnataka\t\t', 'Karnataka\t'), ('Gujarat\t', 'Gujarat'), ('Goa\t', 'Goa'), ('Uttar Pradesh\t', 'Uttar Pradesh\t'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal\t', 'West Bengal\t'), ('Tripura', 'Tripura'), ('Telangana\t', 'Telangana\t'), ('Tamil Nadu', 'Tamil Nadu\t'), ('Sikkim', 'Sikkim'), ('Rajasthan', 'Rajasthan'), ('Punjab', 'Punjab'), ('Odisha\t', 'Odisha\t'), ('Nagaland', 'Nagaland'), ('Mizoram', 'Mizoram'), ('Meghalaya\t', 'Meghalaya\t'), ('Manipur', 'Manipur'), ('Maharashtra', 'Maharashtra'), ('Madhya Pradesh\t', 'Madhya Pradesh\t'), ('Kerala', 'Kerala'), ('Jharkhand', 'Jharkhand'), ('Himachal Pradesh\t', 'Himachal Pradesh\t'), ('Haryana', 'Haryana'), ('Chhattisgarh', 'Chhattisgarh'), ('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Arunachal Pradesh\t', 'Arunachal Pradesh')], max_length=50)),
                ('mobile', models.PositiveIntegerField()),
                ('job_city', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimage')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
